FROM rayproject/ray:2.44.1-py312-gpu

ENV DEBIAN_FRONTEND=noninteractive \
    PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    TORCH_CUDA_ARCH_LIST="7.0;8.0" \
    PIP_NO_CACHE_DIR=off \
    PIP_DISABLE_PIP_VERSION_CHECK=on \
    PIP_DEFAULT_TIMEOUT=100

# dependencies to support ray[llm]
USER root
RUN pip install \
    "ray[serve,llm]==2.44.1" \
    "vllm>=0.7.2" \
    "xgrammar==0.1.18" \
    "pynvml==12.0.0" \
    "httpx" \
    torch \
    transformers \
    accelerate
USER 1000:1000
