FROM rayproject/ray:2.44.1-py312-gpu

ENV DEBIAN_FRONTEND=noninteractive \
    PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    TORCH_CUDA_ARCH_LIST="7.0;8.0"

WORKDIR /app

USER root

# Repeat the packages required for this ray[llm]
RUN --mount=type=cache,target=/root/.cache/pip pip install \
    "ray[serve,llm]==2.44.1" \
    "vllm>=0.7.2" \
    "xgrammar==0.1.18" \
    "pynvml==12.0.0" \
    "httpx" \
    torch \
    transformers \
    accelerate

# Copy application
COPY serve.py /app/
COPY ".serve.env" /app/
COPY --chmod=755 start.sh /app/

USER 1000:1000

EXPOSE 8000
CMD ["/app/start.sh"]
