global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'ray'
    file_sd_configs:
      - files:
        - '/etc/targets/prom_metrics_service_discovery.json'
